# docker-compose.yml

version: '3.9'
services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=mydb;Username=postgres;Password=postgres
    depends_on:
      - postgres


  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"  # Exposing port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
